# Generated by Django 5.2.7 on 2025-10-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "especies",
                    models.CharField(
                        choices=[
                            ("DOG", "Cachorro"),
                            ("CAT", "Gato"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("raca", models.CharField(blank=True, max_length=100, null=True)),
                ("data_nasc", models.DateField(verbose_name="Data de Nascimento")),
                ("obs", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["nome"],
            },
        ),
    ]
