# Generated by Django 5.2.7 on 2025-10-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_preco"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
